name: 'Welcome new contributors'

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  greet-the-contributor:
    runs-on: ubuntu-latest
    steps:
    - uses: garg3133/welcome-new-contributors@v1.1
      with:
        token: ${{ secrets.BOT_ACCESS_TOKEN }}
        is-oauth-token: true
        issue-message: 'Hi! Thanks for opening your first issue at JagratiWebApp :rocket: We really appreciate it. :raised_hands: Someone from our team will get back here soon.'
        pr-message: 'Congratulations for making your first Pull Request at JagratiWebApp!! :tada: Someone from our team will review it soon.'
